### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by CasperWA**
### Update dependencies

Automatically created PR from [`ci/dependabot-updates`](https://github.com/aiidateam/aiida-optimade/tree/ci/dependabot-updates).
It should be automagically merged into `main` upon CI success.

For more information see the ["Dependabot updates" workflow](https://github.com/aiidateam/aiida-optimade/blob/develop/.github/workflows/ci_dependabot.yml).

### CODE REVIEW

**Review by unkcpz — COMMENTED** [review]
@CasperWA thanks! The `psql_dos` -> `core.psql_dos` and the CLI are two essential changes that slightly breaks backward compatibility as I know and you all addressed, then I think it is all fine. Could you also set `AIIDA_WARN_v3=1` to see if a deprecated API is used?

**Comment by unkcpz** [comment]
Also, the py3.10 test always failed from the last migration to 2.0. I turn it off since I thought it failed randomly, but it keeps on appearing, I assume it is related to some issue? Do you have any clue?

**Comment by CasperWA** [comment]
> Also, the py3.10 test always failed from the last migration to 2.0. I turn it off since I thought it failed randomly, but it keeps on appearing, I assume it is related to some issue? Do you have any clue?

I do not have a clear clue, but the tests that are failing are perhaps quite fragile. They are depending on some subprocesses and such, and may therefore break more easily when changing Python version. I'll have to investigate further, you are also welcome. At least an issue should be made on it to follow up.

**Comment by CasperWA** [comment]
> @CasperWA thanks! The `psql_dos` -> `core.psql_dos` and the CLI are two essential changes that slightly breaks backward compatibility as I know and you all addressed, then I think it is all fine. Could you also set `AIIDA_WARN_v3=1` to see if a deprecated API is used?

I'm no sure what this is. Where should I set it? As an environment variable when running the `pytest` system?

And indeed, this is slightly backwards compatible. How was it you set up the compatibility table previously? Is this something you could perhaps add to to this PR. Or even better, create a new PR for after this one has been merged, before we then immediately afterwards create a new AiiDA-OPTIMADE release?

**Comment by unkcpz** [comment]
> I'm no sure what this is. Where should I set it? As an environment variable when running the pytest system?

Yes, as an environment variable by `export AIIDA_WARN_v3=1` should work I think. 

>  Or even better, create a new PR for after this one has been merged, before we then immediately afterwards create a new AiiDA-OPTIMADE release?

No problem, I'll check and create another PR for it.

**Review by unkcpz — APPROVED** [review]

**Pull request merged**
